[package]
name = "fake"
version = "0.2.0"
authors = ["Joshua Davey <josh@joshuadavey.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
structopt = "0.3"
rand = "0.8"
strena = { git = "https://github.com/jgdavey/strena.git", rev = "f6122b94ff605f8dafa435d1bca757ce975f7031" }
tokio = { version = "1.3", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
